---
title: "weather"
author: "Rayna M Harris"
date: "11/1/2021"
output: html_document
---

```{r setup, echo = T, message = T, results = T, warning = T}

knitr::opts_chunk$set(echo = T, message = T, 
                      results = T, warning = T,
                      fig.path = '../images/')

library(tidyverse)
library(lubridate)
library(cowplot)
library(magick)
library(viridis)
library(scales)
library(ggridges)

noaa <- image_read("../images/noaa.png")
photo_file <- image_read( "../images/photo-tahoe.png")

```
## Austin Versus Squaw ~ March 2021

```{r weather-austinsquaw}

weather <- read_csv("../data/weather.csv") %>%
  mutate(date = DATE) %>% 
  select(date, NAME, TAVG, TMAX, TMIN) %>%
  mutate(city = "Squaw Valley, CA")
head(weather)

weather4 <- read_csv("../data/weather4.csv") %>%
  mutate(date = DATE) %>% 
  select(date, NAME, TAVG, TMAX, TMIN) %>%
  mutate(city = "Austin, TX")
head(weather4)
 
weather <- rbind(weather, weather4) %>%
    filter(date <= as.Date("2020-12-31"))

ggplot(weather, aes(date, ymin = TMIN, ymax = TMAX, color = TMAX)) +
  geom_linerange(size = 1, alpha = 0.75) +
  scale_color_viridis(discrete = F, limits = c(1,110)) +
  scale_x_date(labels = date_format("%b"), breaks = date_breaks("month")) +
  ylim(0, 110) +
  labs(
    title = "2020 Weather Radials",
    x = NULL,
    y = NULL,
    color = expression(paste("Max\ntemp (",degree,"F)")) ,
    caption = "Data from NOAA www.ncdc.noaa.gov/cdo-web/datasets"
  ) +
  coord_polar(start = 3.14) +
  theme_cowplot() +
  theme(legend.position = "right",
        axis.ticks.y = element_blank()) +
  facet_wrap(~city)
```

## Davis, Truckee, and Fairbanks

```{r weather-coldcities, fig.width=6, fig.height=3.3}

dtf <- read_csv("../data/weather-2021-10-21.csv") %>%
  select(STATION, NAME, DATE, TMIN, TMAX, TAVG) %>%
  mutate(TMID = ((TMIN + TMAX)/2),
         NAME = factor(NAME),
         STATION = factor(STATION))  
head(dtf)
tail(dtf)
summary(dtf)

# rename levels
levels(dtf$NAME) 
levels(dtf$NAME) <- c("Fairbanks, AK", "Sacramento, CA", "Truckee, CA")

ggplot(dtf, aes(x = DATE, ymin = TMIN, ymax = TMAX, color = TMID)) +
  geom_linerange(size = 1, alpha = 0.75) +
  scale_color_viridis(discrete = F, limits = c(-50,100)) +
  scale_x_date(labels = date_format("%b"), breaks = date_breaks("month")) +
  ylim(-50,100) +
  labs(
    title = "Weather Radials",
    caption = "The lines connect the daily minimum and maximum temperatures and are colored by the mid temp.",
    x = NULL,
    y = NULL,
    color = expression(paste("Mid\ntemp (",degree,"F)")) ,
    subtitle = "Data from NOAA www.ncdc.noaa.gov/cdo-web/datasets"
  ) +
  coord_polar(start = 3.14) +
  theme_cowplot() +
  theme(legend.position = "right",
       # axis.text.y = element_blank(), 
        axis.ticks.y = element_blank()) +
  facet_wrap(~NAME)


```

## Squaw, Heavenly, Vail, Mt Hood

```{r weather-oct-22, fig.width=6, fig.height=3.3}

df <- read_csv("../data/weather-2021-10-22.csv") %>%
  select(STATION, NAME, DATE, SNWD) %>%
  filter(!grepl("VAIL", NAME)) %>%
  mutate(NAME = factor(NAME),
         STATION = factor(STATION)) %>%
  drop_na()
summary(df)

# rename levels
levels(df$NAME) 
levels(df$NAME) <- c("Heavenly, NV", "Mt Hood, OR", "Squaw Valley, CA")
levels(df$NAME) 

skicolors <- c("#e53735", "#2a82c4", "#231a49" )

a <- df %>%
  filter(DATE >= as.Date("2021-10-01")) %>%
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    geom_point() +
    geom_line() +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall this month",
         color = NULL) +
    theme_minimal() +
    theme(legend.position = c(0.35, 0.8),
          axis.text.x = element_text(angle = 45)) +
  scale_color_manual(values = skicolors)

b <- df %>%
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    geom_point(size = 0.5, alpha = 0.5) +
    geom_line(alpha = 0.5) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall  last 360 days",
         #caption = "Data from NOAA www.ncdc.noaa.gov/cdo-web/datasets",
         color = NULL) +
    theme_minimal() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45))  +
  scale_color_manual(values = skicolors)

plot_grid(a,b, nrow = 1)
```

```{r weather-oct-22-long, fig.width=4, fig.height=6}
plot_grid(a,b, nrow = 1)
```


## October 25

```{r weather-oct-25, fig.width=6, fig.height=3.3}

oct25 <- read_csv("../data/weather-2021-10-25.csv") %>%
  select(STATION, NAME, DATE, SNWD) %>%
  filter(!grepl("VAIL", NAME)) %>%
  mutate(NAME = factor(NAME),
         STATION = factor(STATION)) %>%
  drop_na()
summary(oct25)

# rename levels
levels(oct25$NAME) 
levels(oct25$NAME) <- c("Heavenly, NV", "Mt Hood, OR", 
                        "Mt Rose, NV", "Soda Springs, CA",  "Squaw Valley, CA")
levels(oct25$NAME) 

skicolors <- c("#e53735", "#2a82c4", "#11539f", "#2b7496", "#231a49" )

oct25 %>%
  ggplot(aes(x = DATE, y = SNWD)) +
    #geom_point(size = 0.5) +
    geom_line() +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall this month",
         color = NULL) +
    theme_minimal() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45)) +
  scale_color_manual(values = skicolors) +
  facet_wrap(~NAME, nrow = 1)
```

## November 11

```{r weather-nov-11, fig.width=6, fig.height=3.3}



nov11 <- read_csv("../data/weather-2021-11-11.csv") %>%
  select(STATION, NAME, DATE, SNWD) %>%
  mutate(NAME = factor(NAME),
         STATION = factor(STATION))   %>% 
  mutate(DATE2 = DATE) %>%
  separate(DATE2, c("YEAR", "MONTH", "DAY"))  
summary(nov11)

# rename levels
levels(nov11$NAME) 
levels(nov11$NAME) <- c("Heavenly, NV",  
                        "Mt Rose, NV",  
                        "Soda Springs, CA",
                        "Squaw Valley, CA")
levels(nov11$NAME) 

skicolors <- c("#e53735",  "#11539f", "#fbd249",  "#231a49" )

p <- nov11 %>% 
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall around Lake Tahoe",
         color = NULL) +
    theme_bw() +
    theme(#legend.position = "none",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("month")) + 
  facet_grid(~YEAR, drop = T, 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 38)
p

jpeg(file="../images/weather-nov-11-1.jpg", width=1600, height=800, res = 300)
p
dev.off()

p2 <- nov11 %>% 
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall around Lake Tahoe",
         color = NULL) +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("month"),
               labels = date_format("%b %d")) + 
  facet_grid(~YEAR, drop = T, 
             scales = "free_x", space = "free_x") 
p2

jpeg(file="../images/weather-nov-11-2.jpg", width=1650, height=1650, res = 300)
p2
dev.off()

p3 <- ggplot(nov11, aes(x = DATE, y = NAME, 
                        height = SNWD, fill = NAME)) +
  geom_density_ridges(stat = "identity", alpha = 0.75, scale = 4) +
  scale_fill_manual(values = skicolors) +
  theme_cowplot() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_x_date(breaks = date_breaks("month"), 
               labels = date_format("%b %d")) +
  labs(subtitle = "Snow Depth around Lake Tahoe, Oct 2020 - Nov 2021",
       y = NULL,
       caption = "Daily summaries collected from https://www.ncdc.noaa.gov/cdo-web/search",
      x = "2020                                                         2021            ") 
p3

#jpeg(file="../images/weather-nov-11-3.jpg", width=1600, height=1200, res = 300)
#p3
#dev.off()

p4 <- ggdraw() + 
  draw_image(photo_file, scale = 0.25, x = -0.365, y =  0.3 ) +
  draw_plot(p3)
p4

jpeg(file="../images/weather-nov-11-4.jpg", width=1600, height=1200, res = 300)
p4
dev.off()


```

