---
title: "weather-ggridges"
author: "Rayna M Harris"
date: "11/1/2021"
output: md_document
---

## Weather - ggridges

```{r setup, echo = T, message = T, results = T, warning = T}

knitr::opts_chunk$set(echo = T, message = T, 
                      results = T, warning = T,
                      fig.path = '../images/')

library(tidyverse)
library(lubridate)
library(cowplot)
library(viridis)
library(scales)
library(ggridges)

```


```{r weather-ggridges, fig.width=6, fig.height=3.3}
#
dec22 <- read_csv("../data/weather-2021-12-22.csv") %>%
  select(STATION, NAME, DATE, SNWD) %>%
  mutate(NAME = factor(NAME),
         STATION = factor(STATION))   %>% 
  mutate(DATE2 = DATE) %>%
  separate(DATE2, c("YEAR", "MONTH", "DAY"))  
summary(dec22)

# rename levels
levels(dec22$NAME) 
levels(dec22$NAME) <- c("Heavenly, NV",  
                        "Mt Rose, NV",  
                        "Soda Springs, CA",
                        "Squaw Valley, CA")
levels(dec22$NAME) 

skicolors <- c("#e53735",  "#11539f", "#fbd249",  "#231a49" )

p <- dec22 %>% 
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall around Lake Tahoe",
         color = NULL) +
    theme_bw() +
    theme(#legend.position = "none",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("month")) + 
  facet_grid(~YEAR, drop = T, 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 38)
p

jpeg(file="../images/weather-ggridges-1.jpg", width=1600, height=800, res = 300)
p
dev.off()

p2 <- dec22 %>% 
  ggplot(aes(x = DATE, y = SNWD, color = NAME)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall around Lake Tahoe",
         color = NULL) +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("month"),
               labels = date_format("%b %d")) + 
  facet_grid(~YEAR, drop = T, 
             scales = "free_x", space = "free_x") 
p2

jpeg(file="../images/weather-ggridges-2.jpg", width=1650, height=1650, res = 300)
p2
dev.off()

p3 <- ggplot(dec22, aes(x = DATE, y = NAME, 
                        height = SNWD, fill = NAME)) +
  geom_density_ridges(stat = "identity", alpha = 0.75, scale = 4) +
  scale_fill_manual(values = skicolors) +
  theme_cowplot() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  scale_x_date(breaks = date_breaks("year"), 
               labels = date_format("%b %d %Y")) +
  labs(subtitle = "Snow Depth around Lake Tahoe, Oct 2020 - Nov 2021",
       y = NULL,
       caption = "Daily summaries collected from https://www.ncdc.noaa.gov/cdo-web/search",
      x =  NULL) 
p3

jpeg(file="../images/weather-ggridges-3.jpg", width=1600, height=1200, res = 300)
p3
dev.off()



dec22 %>% 
  filter(NAME == "Squaw Valley, CA") %>%
  ggplot(aes(x = DATE, y = SNWD)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall at the Squaw Valley, CA NOAA Station",
         color = NULL) +
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  #scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("year")) + 
  #facet_wrap(~NAME, nrow  = 1) +
  geom_hline(yintercept = 55)

dec22 %>% 
  filter(NAME == "Squaw Valley, CA") %>%
  ggplot(aes(x = DATE, y = SNWD)) +
    #geom_point(size = 0.1, alpha = 0.5) +
    geom_line(alpha = 0.9) +
    labs(x = NULL, y = "Snow depth (in)",
         subtitle = "Snowfall at the Squaw Valley, CA NOAA Station",
         color = NULL) +
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, 
                                     hjust = 1)) +
  #scale_color_manual(values = skicolors) +
  scale_x_date(breaks = date_breaks("year"))

```

```{r weather-blizard}
df <- read_csv("../data/weather-2021-12-30.csv") %>%
  select(STATION, NAME, DATE, SNWD) %>%
  mutate(DATE2 = DATE) %>%
  separate(DATE2, c("YEAR", "MONTH", "DAY"))  %>%
  #filter(NAME == "SQUAW VALLEY G.C., CA US") %>%
    mutate(NAME = factor(NAME),
         STATION = factor(STATION),
         YEAR = as.numeric(YEAR))   %>% 
  droplevels() %>%
  drop_na()  %>%
  group_by(NAME, YEAR) %>%
  summarize(SNWD_MAX = max(SNWD))
summary(df)

df %>%
  ggplot(aes(x = reorder(YEAR, SNWD_MAX), y = SNWD_MAX)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

df %>%
  ggplot(aes(x = YEAR, y = SNWD_MAX)) +
  geom_bar(stat = "identity") +
  facet_wrap(~NAME)

```

```{r}
hourly <- read_csv("../data/precipitation-2021-12-30.csv") %>%
  filter(HPCP != 999.99) %>%
  mutate(hour = lubridate::hour(DATE),
         day = lubridate::day(DATE),
         month = lubridate::month(DATE),
         year = lubridate::year(DATE)) 

head(hourly)
summary(hourly)



daily <- hourly %>%
  group_by(month, day, year) %>%
  summarize(DPCP = sum(HPCP))
head(daily)
summary(daily)


montly <- hourly %>%
  group_by(month, year) %>%
  summarize(MPCP = sum(HPCP))
head(montly)
summary(montly)


yearly <- hourly %>%
  group_by(year) %>%
  summarize(YPCP = sum(HPCP))
head(yearly)
summary(yearly)

yearly %>%
  ggplot(aes(x = year, y = YPCP)) +
  geom_line()

montly %>%
  filter(year > 2004) %>%
  ggplot(aes(x = month, y = MPCP)) +
  geom_line() +
  facet_wrap(~year)
```

